"""empty message

Revision ID: 5ef0a13ec768
Revises: a31248020c7e
Create Date: 2022-01-21 15:32:41.818508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef0a13ec768'
down_revision = 'a31248020c7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_accounts', sa.Column('google_id', sa.String(length=255), nullable=False))
    op.drop_column('service_accounts', 'calendar_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_accounts', sa.Column('calendar_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('service_accounts', 'google_id')
    # ### end Alembic commands ###
