"""empty message

Revision ID: 71e633a22ca0
Revises: c124043416ef
Create Date: 2022-01-21 15:08:10.186233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e633a22ca0'
down_revision = 'c124043416ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant', 'email')
    op.drop_column('tenant', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('tenant', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
