"""empty message

Revision ID: c124043416ef
Revises: c925c60a033e
Create Date: 2022-01-20 14:29:12.297526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c124043416ef'
down_revision = 'c925c60a033e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('building',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('room', sa.Column('floor', sa.Integer(), nullable=True))
    op.add_column('room', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('room', sa.Column('building_id', sa.Integer(), nullable=True))
    op.add_column('room', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'room', 'building', ['building_id'], ['id'])
    op.create_foreign_key(None, 'room', 'city', ['city_id'], ['id'])
    op.drop_column('room', 'room_number')
    op.drop_column('room', 'city')
    op.drop_column('room', 'building')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('building', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('room', sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('room', sa.Column('room_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'room', type_='foreignkey')
    op.drop_constraint(None, 'room', type_='foreignkey')
    op.drop_column('room', 'city_id')
    op.drop_column('room', 'building_id')
    op.drop_column('room', 'name')
    op.drop_column('room', 'floor')
    op.drop_table('city')
    op.drop_table('building')
    # ### end Alembic commands ###
